// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using llama.cpp_models_preset_manager;

#nullable disable

namespace llama.cpp_models_preset_manager.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("llama.cpp_models_preset_manager.Models.AiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AIModel");
                });

            modelBuilder.Entity("llama.cpp_models_preset_manager.Models.AiModelFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AIModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AIModelId");

                    b.ToTable("AIModelFlag");
                });

            modelBuilder.Entity("llama.cpp_models_preset_manager.Models.Flag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Flag");
                });

            modelBuilder.Entity("llama.cpp_models_preset_manager.Models.KVConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("KVConfig");
                });

            modelBuilder.Entity("llama.cpp_models_preset_manager.Models.AiModelFlag", b =>
                {
                    b.HasOne("llama.cpp_models_preset_manager.Models.AiModel", "AIModel")
                        .WithMany("Flags")
                        .HasForeignKey("AIModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIModel");
                });

            modelBuilder.Entity("llama.cpp_models_preset_manager.Models.AiModel", b =>
                {
                    b.Navigation("Flags");
                });
#pragma warning restore 612, 618
        }
    }
}
